Сделал гайд по установке и настройке
vanya-beat/bmstu_cpp_course pull request #2
Opened 2024-09-30 17:27 UTC by Ifanfomin

Сделал гайд по установке ssh подключения к GitHub, установке докера и выполнению домашней работы в VSCode на Ubuntu

2024-09-30 17:28 UTC, Ifanfomin commented
Первый раз делаю рексвекст, возможны недочеты

2024-09-30 17:40 UTC, vanya-beat requested changes
Удалите пожалуйста код, задачки, а то люди будут его случайно себе форкать

2024-09-30 17:49 UTC, Ifanfomin commented
Нужно ведь убрать коммит из истории? Я просто не знаю как убрать коммит из истории

2024-10-06 14:13 UTC, vanya-beat commented
Ладно придется мне поправить

2024-10-06 14:14 UTC, closed without merging